# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '8ce8274b-af75-40ef-abfe-1de1451b2c71'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/luchenzo7/ARMPipeline-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName pipeprojy'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
